apiVersion: v1
kind: Service
metadata:
  name: sinchew-service
  namespace: default
spec:
  selector:
    app: sinchew-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
